import 'dart:math';

import 'package:hive_ce/hive.dart';

/// Persists the next-attempt timestamp (millis since epoch) for outbox items
/// that have failed with a retryable error.
///
/// Stored separately from the item models so that we don't need to touch the
/// Hive adapters of every domain model just to carry a backoff field, and
/// separately from [OutboxErrorStore] because the two have different
/// lifecycles: backoff is per *attempt* and is cleared on success, whereas a
/// permanent error survives until the user retries or deletes.
///
/// The key is the [OutboxItem.id]:
///   * for `create` operations this is the same as the model's `localId`,
///   * for other operations it is the random uuid generated by `OutboxItem`.
class OutboxBackoffStore {
  // ---- Singleton boilerplate ----
  OutboxBackoffStore._internal();
  static final OutboxBackoffStore _instance = OutboxBackoffStore._internal();
  factory OutboxBackoffStore() => _instance;

  // ---- Class implementation ----
  static const boxName = 'outbox_sync_backoff';

  /// Number of consecutive failures recorded for each item, used as the
  /// exponent in the backoff formula. Co-located with the next-attempt
  /// timestamp under the same key but with a `:n` suffix to avoid needing a
  /// second box.
  static const _attemptSuffix = ':n';

  Box<int> get _box => Hive.box<int>(boxName);

  /// Open the backing box. Safe to call multiple times.
  static Future<void> init() async {
    if (!Hive.isBoxOpen(boxName)) {
      await Hive.openBox<int>(boxName);
    }
  }

  /// Whether [itemId] is currently in a backoff window and should not be
  /// retried yet by `syncRepository`.
  bool isBackedOff(String itemId, {DateTime? now}) {
    final ts = _box.get(itemId);
    if (ts == null) return false;
    final n = (now ?? DateTime.now()).millisecondsSinceEpoch;
    return ts > n;
  }

  /// Returns the recorded next-attempt time for [itemId], or null if none.
  DateTime? nextAttemptAt(String itemId) {
    final ts = _box.get(itemId);
    return ts == null ? null : DateTime.fromMillisecondsSinceEpoch(ts);
  }

  /// Record a fresh failure for [itemId] and return the new next-attempt
  /// time. Schedule is exponential with jitter:
  ///
  ///   delay = clamp(base * 2 ^ (attempt - 1), base, cap) ± jitter
  ///
  /// where attempt is the number of consecutive failures including this
  /// one. Defaults: base = 30s, cap = 1h, jitter = ±20%.
  ///
  /// `random` is exposed for deterministic tests.
  DateTime recordFailure(
    String itemId, {
    DateTime? now,
    Random? random,
    Duration base = const Duration(seconds: 30),
    Duration cap = const Duration(hours: 1),
    double jitterFraction = 0.2,
  }) {
    final attempt = (_box.get(_attemptKey(itemId)) ?? 0) + 1;
    final n = now ?? DateTime.now();
    final delay = computeBackoff(
      attempt: attempt,
      base: base,
      cap: cap,
      jitterFraction: jitterFraction,
      random: random,
    );
    final next = n.add(delay);
    _box.put(itemId, next.millisecondsSinceEpoch);
    _box.put(_attemptKey(itemId), attempt);
    return next;
  }

  /// Clear any backoff state for [itemId] (success, permanent failure, or
  /// explicit user retry / delete).
  Future<void> clear(String itemId) async {
    await _box.delete(itemId);
    await _box.delete(_attemptKey(itemId));
  }

  /// Number of consecutive failures recorded for [itemId]. Mainly exposed
  /// for diagnostics and tests.
  int attemptCount(String itemId) =>
      _box.get(_attemptKey(itemId), defaultValue: 0) ?? 0;

  String _attemptKey(String itemId) => '$itemId$_attemptSuffix';
}

/// Pure helper, exposed for testing.
///
/// Returns `clamp(base * 2 ^ (attempt - 1), base, cap) ± jitter`.
/// `attempt` must be >= 1.
Duration computeBackoff({
  required int attempt,
  required Duration base,
  required Duration cap,
  required double jitterFraction,
  Random? random,
}) {
  assert(attempt >= 1, 'attempt must be >= 1');
  assert(jitterFraction >= 0 && jitterFraction < 1);

  // Exponential growth, with overflow-safe handling for very large attempt
  // counts (we cap before computing 2^n directly).
  final shift = (attempt - 1).clamp(0, 30); // 2^30 ms = ~12 days, well past cap
  final raw = base.inMilliseconds * (1 << shift);
  final capped = raw.clamp(base.inMilliseconds, cap.inMilliseconds);

  // Symmetric jitter in [-jitterFraction, +jitterFraction] of the capped
  // delay. We use a fresh Random by default; tests can pass a seeded one.
  final r = random ?? Random();
  final jitter = (r.nextDouble() * 2 - 1) * jitterFraction * capped;
  final withJitter = (capped + jitter).round();

  // Always wait at least `base` to avoid immediate hot-loops on tiny jitter.
  final clamped = withJitter < base.inMilliseconds
      ? base.inMilliseconds
      : withJitter;
  return Duration(milliseconds: clamped);
}
